# Site wide configuration

title: Utopian Concept LLC
description: "Utopian Concept LLC is a bespoke development company. Experienced with all aspects of development ranging from web, mobile, desktop, and client/server."
logo: # 120x120 px default image used for Twitter summary card
teaser: default-teaser.jpg # 400x250 px default teaser image used in image archive grid
locale: en_US
url: https://utopianconcept.com
enforce_ssl: utopianconcept.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
lsi: true
markdown: kramdown
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-archives

# Site owner
owner:
  name: Ray Clanan
  email: rclanan@utopianconcept.com
  twitter: utopianconcept
  facebook: utopianconcept
  fbAppId: 619415181409836
  instagram: rclanan
  stackoverflow: https://stackoverflow.com/users/139002/rclanan #http://stackoverflow.com/users/123456/username
  linkedin: raymondclanan #username
  tumblr: rclanan #username
  lastfm: rclanan #username
  pinterest: rclanan #username
  dribbble: rclanan #username
  youtube: rclanan #username
  soundcloud: rclanan #username
  github: utopianconcept
  github-repo: https://github.com/rclanan/rclanan.github.io
  google:
    ad-client: ca-pub-9088055479182184
    ad-slot: 1766459353
    analytics: UA-42068834-1
    plus: https://plus.google.com/+UtopianConceptLLCFranklin/posts
    verify:
  bing:
    verify: 9BAC30D0133304B52E5D583E9639401F
  alexa:
    verify: sGS-ACEaZN_7mmf7rVEEkq4Ky6w
  yandex:
    verify: 78c0d8d209910284
  bio: "Another day, another byte processed."
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: utopianconcept

# Plugin: jekyll-archives

jekyll-archives:
  enabled:
    - tags
    - year
  layouts:
    year: year_index
    tag: tag_index
  permalinks:
    year: /:year/
    tag: /tag/:name/

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "vendor"]
